FROM python:3.12-slim

RUN apt-get update && apt-get install -y gcc && apt-get clean

RUN pip install --no-cache-dir \
    fastapi \
    uvicorn \
    faker \
    confluent-kafka

WORKDIR /opt/airflow

CMD ["uvicorn", "src.api.generator:app", "--host", "0.0.0.0", "--port", "8000"]